"""Added 3 new columns to user table

Revision ID: 9a2353d7b7d0
Revises: f1181366dbfc
Create Date: 2026-02-17 20:41:18.274061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2353d7b7d0'
down_revision = 'f1181366dbfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('branch_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('customer_support_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('otp_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires')
    op.drop_column('users', 'customer_support_code')
    op.drop_column('users', 'branch_code')
    # ### end Alembic commands ###
