"""Initial migration

Revision ID: f1181366dbfc
Revises: 
Create Date: 2026-01-07 22:49:39.695054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1181366dbfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('audit_type', sa.Enum('UNKNOWN', 'CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'VIEW', name='audittypeenum'), nullable=False),
    sa.Column('user_type', sa.Enum('UNKNOWN', 'GUEST', 'CUSTOMER', 'STAFF', 'VENDOR', 'CONTENTMANAGER', 'REPORTANALYST', 'INVENTORYMANAGER', 'SUPERVISOR', 'SUPERADMIN', name='userroleenum'), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=True),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.String(length=255), nullable=True),
    sa.Column('processor_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.String(length=255), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_trail_id'), 'audit_trail', ['id'], unique=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('normalized_email', sa.String(length=255), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('gender', sa.Enum('UNKNOWN', 'MALE', 'FEMALE', 'OTHERS', name='genderenum'), nullable=False),
    sa.Column('user_role', sa.Enum('UNKNOWN', 'GUEST', 'CUSTOMER', 'STAFF', 'VENDOR', 'CONTENTMANAGER', 'REPORTANALYST', 'INVENTORYMANAGER', 'SUPERVISOR', 'SUPERADMIN', name='userroleenum'), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('otp', sa.String(length=50), nullable=True),
    sa.Column('use_otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('lockout_date_time', sa.DateTime(), nullable=True),
    sa.Column('lockout_enabled', sa.Boolean(), nullable=False),
    sa.Column('access_failed_count', sa.Integer(), nullable=False),
    sa.Column('profile_image_URL', sa.String(length=500), nullable=True),
    sa.Column('profile_image_file_name', sa.String(length=255), nullable=True),
    sa.Column('upload_profile_image_date_time', sa.DateTime(), nullable=True),
    sa.Column('profile_URL', sa.String(length=500), nullable=True),
    sa.Column('selected_theme', sa.String(length=50), nullable=True),
    sa.Column('selected_theme_date_time', sa.DateTime(), nullable=True),
    sa.Column('user_GUID', sa.String(length=255), nullable=True),
    sa.Column('user_logged_In', sa.Boolean(), nullable=False),
    sa.Column('default_password', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('security_stamp', sa.String(length=500), nullable=True),
    sa.Column('last_logged_in_date', sa.DateTime(), nullable=True),
    sa.Column('last_password_changed_date', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('verified_date', sa.DateTime(), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.String(length=1000), nullable=True),
    sa.Column('refresh_token', sa.String(length=500), nullable=True),
    sa.Column('refresh_token_expires', sa.DateTime(), nullable=True),
    sa.Column('revoked_token_date', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.String(length=255), nullable=True),
    sa.Column('replaced_by_token', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.String(length=255), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_normalized_email'), 'users', ['normalized_email'], unique=True)
    op.create_index(op.f('ix_users_user_GUID'), 'users', ['user_GUID'], unique=True)
    op.create_index(op.f('ix_users_verification_token'), 'users', ['verification_token'], unique=True)
    op.create_table('addresses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('address_type', sa.Enum('UNKNOWN', 'BILLING', 'SHIPPING', 'BRANCH', 'SUPPLIER', 'WAREHOUSE', name='addresstypeenum'), nullable=False),
    sa.Column('address_line1', sa.String(length=500), nullable=True),
    sa.Column('address_line2', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.String(length=255), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_id'), 'addresses', ['id'], unique=False)
    op.create_index(op.f('ix_addresses_is_default'), 'addresses', ['is_default'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.create_table('branch_locations',
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('branch_code', sa.String(length=50), nullable=True),
    sa.Column('branch_type', sa.Enum('UNKNOWN', 'WAREHOUSE', 'RETAIL', 'OFFICE', name='branchtypeenum'), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('branch_phone', sa.String(length=50), nullable=True),
    sa.Column('branch_email', sa.String(length=255), nullable=True),
    sa.Column('operating_hours', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('size_sqft', sa.Integer(), nullable=True),
    sa.Column('is_operational', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_modified_by', sa.String(length=255), nullable=True),
    sa.Column('last_modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_locations_branch_code'), 'branch_locations', ['branch_code'], unique=True)
    op.create_index(op.f('ix_branch_locations_id'), 'branch_locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branch_locations_id'), table_name='branch_locations')
    op.drop_index(op.f('ix_branch_locations_branch_code'), table_name='branch_locations')
    op.drop_table('branch_locations')
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_is_default'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_verification_token'), table_name='users')
    op.drop_index(op.f('ix_users_user_GUID'), table_name='users')
    op.drop_index(op.f('ix_users_normalized_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_trail_id'), table_name='audit_trail')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
